name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  send-notification:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO_NAME: ${{ github.repository }}
          COMMIT_AUTHOR: ${{ github.actor }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_URL: ${{ github.event.repository.html_url }}/commit/${{ github.sha }}
          COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
          COMMIT_BRANCH: ${{ github.ref }}
        run: |
          PAYLOAD="{\"embeds\": [{\"author\": {\"name\": \"${COMMIT_AUTHOR}\", \"icon_url\": \"${{ github.event.sender.avatar_url }}\"}, \"title\": \"New code has been pushed to the repository\", \"description\": \"Repository: ${REPO_NAME}\", \"color\": 3447003, \"fields\": [{\"name\": \"Commit\", \"value\": \"[${COMMIT_SHA}](${COMMIT_URL})\", \"inline\": true}, {\"name\": \"Message\", \"value\": \"\`\`\`${COMMIT_MESSAGE}\`\`\`\", \"inline\": true}, {\"name\": \"Branch\", \"value\": \"${COMMIT_BRANCH}\", \"inline\": true}], \"footer\": {\"text\": \"Commit Timestamp: ${COMMIT_TIMESTAMP}\"}}]}"
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
